server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: 1234
    url: jdbc:postgresql://localhost:5432/registration
    username: jeet
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format-sql: true
    show-sql: true
  #for mail under spring (check indentation)
  mail:
    host: localhost
    port: 1025
    username: hello
    password: hello

    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
